# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 597d97ba2576768110ea906f9b44b73617dde701a7c970c1631499dbb718e60d732a0848b7189d164bd9a2671b9996a0a64a98f3bd8edbafeea721bc2cadb203

test:
  secret_key_base: ef81dfba33955e821f61a2aadc9af15bc477765a5a003bc9f957cc87bb45b8273b6772b1b33198a701dd0bd55c9bfcaaa85e4943d3cbff5a747bc742d7a0bd57

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
